# Use root/example as user/password credentials
version: '3.1'

services:
  web:
    image: sensor-data
    restart: always
    build: .
    container_name: sesor-data
    ports:
      - 8080:3000
    

  db:
    image: mysql
    restart: always
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: password